import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, BrainCircuit, Flag, ServerCog } from "lucide-react";

export default function Admin() {
  const providers = trpc.admin.providers.useQuery(); const models = trpc.admin.models.useQuery(); const flags = trpc.admin.flags.useQuery();
  return <DashboardLayout><div className="space-y-8 p-5 lg:p-8"><div><p className="text-sm text-cyan-600">CONTROL CENTER</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">P/AI administration</h1><p className="mt-2 text-sm text-muted-foreground">Registry, routing, and feature controls are role-protected and auditable.</p></div><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ServerCog className="size-4 text-cyan-700" /> Providers</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{providers.data?.length ?? 0}</div><p className="mt-1 text-xs text-muted-foreground">Configured gateways</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><BrainCircuit className="size-4 text-cyan-700" /> Models</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{models.data?.length ?? 0}</div><p className="mt-1 text-xs text-muted-foreground">Registered models</p></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Flag className="size-4 text-cyan-700" /> Flags</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{flags.data?.length ?? 0}</div><p className="mt-1 text-xs text-muted-foreground">Runtime controls</p></CardContent></Card></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Activity className="size-5 text-cyan-700" /> Registry health</CardTitle></CardHeader><CardContent className="space-y-3">{providers.data?.length ? providers.data.map(provider => <div key={provider.id} className="flex items-center justify-between rounded-lg border p-4"><div><div className="font-medium">{provider.name}</div><div className="text-xs text-muted-foreground">{provider.kind}</div></div><Badge variant={provider.enabled ? "default" : "secondary"}>{provider.enabled ? "Enabled" : "Disabled"}</Badge></div>) : <p className="text-sm text-muted-foreground">No provider records configured yet. Add credentials through the deployment secret manager before enabling external providers.</p>}</CardContent></Card></div></DashboardLayout>;
}
